# Travis CI configuration for lightpack/framework

before_script:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test_lightpack;'
    - composer self-update
    - composer install
language: php
php:
    - 7.2
services:
    - mysql
cache:
 directories:
   - $HOME/.composer/cache/files
script:
    - vendor/bin/phpunit --verbose
notifications:
    email: false